title: Ekpia Fanihy
description: Ekpia Fanihy
url: "https://ekipafanihy.org/"
# permalink: ':pagetitle/'
# timezone: America/Chicago

# navbar:
#   title: ""
#   left:
# 	- text: "Home"
# 	  href: /
# 	- text: "About"
# 	  href: /about
# 	- text: "Research"
# 	  href: /research_interests
# 	- text: "Programs" 
# 	  href: /programs
# 	- text: "Team"
# 	  href: /team
# 	- text: "Careers / Join"
# 	  href: /careers_join
# 	- text: "News & Media"
# 	  href: https://carabrook.github.io/blog
# 	- text: "Contact / Volunteer" 
# 	  href: /contact_volunteer
# 	- text: "Support Us" 
# 	  href: /support_us

# google_analytics:

# plugins: [jekyll-redirect-from]
 
# assets:
#   sources:
# 	- _assets/css
# 	- _assets/images
# 	- _assets/team


#paginate: 8
#paginate_path: "/page/:num"

# pagination:
#  enabled: true
#   per_page: 10
#   sort_field: 'date'
#   sort_reverse: true

include:
  - _redirects
